/// <reference path="../../typings/index.d.ts"/>
/// <reference path="../config/scene.ts"/>
/// <reference path="../objects/asset.ts"/>
/// <reference path="../objects/button.ts"/>
/// <reference path="../objects/label.ts"/>
/// <reference path="../objects/Scene.ts"/>
/// <reference path="../objects/vector2.ts"/>
/// <reference path="../objects/gameobject.ts"/>
/// <reference path="../objects/starfield.ts"/>
/// <reference path="../managers/collision.ts"/>
/// <reference path="../scenes/start.ts"/>
/// <reference path="../scenes/die.ts"/>
/// <reference path="../scenes/help.ts"/>
/// <reference path="../scenes/exit.ts"/>
/// <reference path="../scenes/playgame.ts"/>  
//# sourceMappingURL=_reference.js.map